# Generated by Django 6.1.1 on 2026-09-04 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True, verbose_name='номер / идентификатор')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='имя в мессенджере')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('survey_in_progress', 'Проходит анкету'), ('survey_completed', 'Анкета заполнена'), ('contacted', 'Связались'), ('rejected', 'Отклонён'), ('hired', 'Нанят')], db_index=True, default='new', max_length=32, verbose_name='статус')),
                ('survey_started_at', models.DateTimeField(blank=True, null=True, verbose_name='анкета начата')),
                ('survey_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='анкета завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
            ],
            options={
                'verbose_name': 'кандидат',
                'verbose_name_plural': 'кандидаты',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст вопроса')),
                ('key', models.SlugField(max_length=64, unique=True, verbose_name='ключ')),
                ('position', models.PositiveIntegerField(unique=True, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее')], max_length=8, verbose_name='направление')),
                ('text', models.TextField(verbose_name='текст')),
                ('transport', models.CharField(max_length=32, verbose_name='транспорт')),
                ('external_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID сообщения транспорта')),
                ('sent_at', models.DateTimeField(db_index=True, verbose_name='время сообщения')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='метаданные')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='recruiting.candidate', verbose_name='кандидат')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('sent_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_candidates', to='recruiting.question', verbose_name='текущий вопрос'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='ответ')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='получен')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='recruiting.candidate', verbose_name='кандидат')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='recruiting.question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'ответы',
                'ordering': ('question__position',),
                'constraints': [models.UniqueConstraint(fields=('candidate', 'question'), name='unique_candidate_question_answer')],
            },
        ),
    ]
