# Generated by Django 6.1.1 on 2026-09-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0002_seed_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='typing_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='печатает до'),
        ),
    ]
