# Generated by Django 6.1.1 on 2026-09-07 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0003_candidate_typing_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='question_needs_prompt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('yes_no', 'Да / Нет')], default='text', max_length=16, verbose_name='тип ответа'),
        ),
        migrations.AddField(
            model_name='question',
            name='show_if_answer',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=3, verbose_name='если ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='show_if_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conditional_questions', to='recruiting.question', verbose_name='показывать после вопроса'),
        ),
    ]
