# Generated by Django 6.1.1 on 2026-09-09 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0006_clean_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('phone_number', models.CharField(max_length=16, unique=True, verbose_name='Рабочий номер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включён в приложении')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='candidate',
            name='external_id',
            field=models.CharField(max_length=64, verbose_name='номер / идентификатор'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='recruiting.phonechannel'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('channel', 'external_id'), name='unique_channel_candidate'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(condition=models.Q(('channel__isnull', True)), fields=('external_id',), name='unique_legacy_candidate'),
        ),
    ]
